Write Nav links when metadata full
OData/AspNetCoreOData pull request #1075
Opened 2023-10-24 08:05 UTC by ElizabethOkerio

2023-10-24 08:32 UTC, habbes commented
@ElizabethOkerio would be great to also show CPU improvements if that's available

2023-10-24 08:38 UTC, habbes commented on test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs
> +        private ODataSerializerContext writeContext;
I think it's strange to have to private `writerContext` fields, where the only difference in the name is the leading `_`. Maybe keep just one of them, or you'll keep both, you can give one a more descriptive name, like `fullMetadataWriteContext`. But since the writer context is initialized per test and shared across methods, maybe it's better not to introduce a new field.

2023-10-24 08:38 UTC, habbes commented on test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs
> +            writeContext = new ODataSerializerContext() { NavigationSource = _customerSet, Model = _model, Path = _path, MetadataLevel = ODataMetadataLevel.Full};
These two are confusing. Maybe rename the latter to `fullMetadataWriteContext`, or remove it altogether.

2023-10-24 08:38 UTC, habbes commented on test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs
> +            writeContext = new ODataSerializerContext() { NavigationSource = _customerSet, Model = _model, Path = _path, MetadataLevel = ODataMetadataLevel.Full};
Another alternative to creating the field is to instantiate the context in the methods that need it, since only 2 methods need the full metadata.

2023-10-24 12:12 UTC, habbes approved these changes

2023-10-24 20:56 UTC, habbes requested changes
If the workload is not following conventions, they could decide to write navigation links even on minimal metadata. So we need a way to ensure that we only skip writing navigation links if the service is following conventions.

2023-10-30 15:28 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +                        resourceContext.WriteNavigationLinks = true;
Does this cover the scenario where the customer is not following conventions?

2023-10-30 16:54 UTC, ElizabethOkerio commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +                        resourceContext.WriteNavigationLinks = true;
yes.

2023-10-30 16:55 UTC, ElizabethOkerio commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +                        resourceContext.WriteNavigationLinks = true;
The method that returns the navigationUrl already does the check..

2023-10-31 09:00 UTC, habbes approved these changes

2023-11-01 05:52 UTC, merged