Fixes #1147: Enable skiptoken handler to handler advanced orderby clause
OData/AspNetCoreOData pull request #1164
Opened 2024-01-30 23:48 UTC by xuzhg

Fixes #1147

### Two parts:

### 1. How to generate the skip token when we have the advanced $orderby?
    
    Based on the discussion and back-compatibility, the PR follows up:
    a) If it's top level property orderby (declared or dynamic or computed), for example: $orderby=name
        the skiptoken will follow up the existing pattern:   `name-'abc'` 

    b) If it's other orderby, for example: $orderby=tolower(substring(name,1,2))
        the skiptoken will only contains the value:   `tx`

### 2. How to consume the skip token when apply the $skiptoken?
   Basically, the skiptoken is coverted to a 'Where(...)' clause (Linq Where function call). Behind the scene, it's a $filter clause.
   The existing implementation cannot handle all and it contains errors.
   This PR is to change it and based on the above truth, we should use our `IFilterBinder` to handle the $skiptoken.

    The logic is that:
    a) Convert the skiptoken and orderby to filter expression
    b) Call IFilterBinder to bind the filter expression to 'Where' Linq expression
    c) Apply the 'Where' to IQueryable.

2024-01-30 23:50 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> -            StringBuilder skipTokenBuilder = new StringBuilder(String.Empty);
Here's the part 1 refactor.

2024-01-30 23:50 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> -            Contract.Assert(query != null);
Here's the part 2 refactor

2024-02-08 07:15 UTC, habbes reviewed
Partial review. Will share more feedback later.

2024-02-09 04:07 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
>                      skipTokenGenerator = (obj) =>
Where is this used?

2024-02-09 04:15 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
>                      skipTokenGenerator = (obj) =>
We should setup analyzers in our codebase to provide hints for such cases.

2024-02-12 07:09 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            IList<OrderByClause> orderByClauses = new List<OrderByClause>();
```suggestion
            List<OrderByClause> orderByClauses = new List<OrderByClause>();
```

2024-02-12 07:09 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            ISet<IEdmProperty> properties = new HashSet<IEdmProperty>();
```suggestion
            HashSet<IEdmProperty> properties = new HashSet<IEdmProperty>();
```

2024-02-12 07:09 UTC, habbes commented on test/Microsoft.AspNetCore.OData.E2E.Tests/SkipToken/SkipTokenControllers.cs
> +            IList<StAddress> stAddresses = new List<StAddress>()
Do you have test cases with dates and negative numbers?

2024-02-12 17:36 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Edm/OrderByClauseHelpers.cs
> +        public static IList<OrderByClause> ToList(this OrderByClause clause)
Keep eyes on List<T> is more efficent than IList<T>. Since it's internal, I am ok to replace it using List<T>.

2024-02-12 17:48 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +                        BuildPropertyContainer(context, source, structuredType, propertiesToExpand, propertiesToInclude, computedProperties, autoSelectedProperties, isSelectingOpenTypeSegments, isSel
Line 377 tells us if 'isSelectedAll == true', we use the 'instance' to save the property mapping. So, when doing binding, we don't need this flag. But, when doing extra "orderby" property binding, we need this flag to tell us whether we should bind property or not.

2024-02-12 17:50 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +            ISet<string> usedPropertyNames = new HashSet<string>();
Maybe you can give us a 'session' about this.

2024-02-12 17:55 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +                usedPropertyNames.Add(name);
Good Suggestion. Let me comment it out and leave a comment for it.

2024-02-12 18:02 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +                propertyValue = Expression.Constant(string.Join(",", names));
That's good suggest. But, I'd say:
"We generate the 'LINQ Expression' as simple as possible so that it can be translated to run on most of LINQ providers." So, Keep it unchanged.

2024-02-12 18:05 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +                if (!usedPropertyNames.Contains(name))
Customer can create a property as "__ordreby__{index}".  It's uncommon but it's valid. Use this code to avoid any potential risk.

2024-02-12 18:07 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
> +                        // Since we don't have the 'Order' value, we should keep the order same as definition order in the schema?
I'd like to here input from @mikepizzo also.
It's just for discussion. I will leave this code unchanged since change it is a behavior breaking changes.

2024-02-12 18:08 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
>                      skipTokenGenerator = (obj) =>
Thanks for suggestion. I'd like to keep it out of this PR scope. I'd like to leave it if we need to refactor for perf.

2024-02-12 18:11 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +        private static IList<KeyValuePair<string, object>> GetPropertyValues(object source, IEdmModel model, IList<OrderByClause> clauses,
No, It's for 'Part-1' to generate the Skip Token string.

2024-02-22 15:44 UTC, habbes requested changes

2024-02-22 15:44 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            IList<string> tokenValueParis = PopulatePropertyValuePairs(skipTokenRawValue);
```suggestion
            IList<string> tokenValuePairs = PopulatePropertyValuePairs(skipTokenRawValue);
```

2024-02-22 15:44 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +                        compare = $"({orderByRaw} gt {orderByValue})";
If the user specified `asc` in the `$orderby` clause, (e.g. `$orderby=Category asc`) this will result in an error because `orderByRaw` will be `Category asc`, which leads to an invalid where clause being generated:

![image](https://github.com/OData/AspNetCoreOData/assets/8460169/4cf5258e-478c-4aae-8d0d-16356e0cd124)

When `desc` is specified, you remove the `desc` keyword using the `RemoveDesc()` helper method. You should do the same thing for `asc`. And probably also add a test case that specifies `asc` explicitly.

2024-02-23 04:04 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            IList<string> tokenValueParis = PopulatePropertyValuePairs(skipTokenRawValue);
Actually, since this list only contains the values (without keys), why not just `tokenValues`?

```suggestion
            List<string> tokenValues = PopulatePropertyValuePairs(skipTokenRawValue);
```

2024-02-23 04:11 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            string lastEquality = null;
nit: The name `lastEquality` might give the impression that this refers to the last or final equality in the loop, but actually it refers to the equality generated in the previous iteration.
```suggestion
            string previousEquality = null;
```

2024-02-23 07:39 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            IList<string> orderBys = orderByOption.RawValue.Split(',');
This will fail if for non-trivial orderby expressions. For example, if you have a function call with multiple parameters like `$orderby=substring(Field, 1),Id`, this will splitinto: `["substring(Field", "1)", "Id"]` which is invalid and will lead to an argument out of range exception because `orderBys` list will have more items than `orderByClauses` list.

Did you intend to support these scenarios in this PR or in a future one? If you want to add support for that in the future then we should detect such cases and throw a meaningful exception that lets the user know that operation is not supported, and then we should create an issue to support that. Otherwise we should handle it better in this PR. Do we have an method that can generate a string representation of an `orderByClause.Expression`  that is a valid OData query expression?

![image](https://github.com/OData/AspNetCoreOData/assets/8460169/fb9b23d2-f1bc-41b7-a152-bd8382b1fd1f)

2024-02-23 07:43 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            Contract.Assert(orderBys.Count == orderByClauses.Count);
Since we knoe of valid user requests that will result in `orderBys.Count` being different from `orderByClauses.Count`, I don't think `Conract.Assert` is sufficient. I think we should throw an exception that tells that user that this particular orderby expression is not supported. Otherwise, it will throw a misleading argument of range exception like the following:

![image](https://github.com/OData/AspNetCoreOData/assets/8460169/22127112-f6b6-4c41-88e0-ccc0c204baf4)

But ideally we should fix the issue such that this doesn't happen because it's not desirable for the server to generate a skiptoken value that it cannot process.

2024-02-26 17:47 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            Contract.Assert(orderBys.Count == orderByClauses.Count);
Since it's tested above and throws exception if it's not matched. It's safe to remove this assert.

2024-02-26 17:53 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +                        compare = $"({orderByRaw} gt {orderByValue})";
Changed the codes and add the test case.

2024-02-26 19:39 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +            IList<string> orderBys = orderByOption.RawValue.Split(',');
Fixed. Can you help to test it again?

2024-02-29 15:31 UTC, habbes approved these changes

2024-02-29 23:04 UTC, merged