Fix test failing after porting feature to OData 8.0-beta
OData/AspNetCoreOData pull request #121
Opened 2021-03-31 09:07 UTC by gathogojr

Fixes test failing subsequent to porting feature to support passing of query options in request body
Related to #119

2021-03-31 16:44 UTC, xuzhg requested changes

2021-03-31 17:30 UTC, gathogojr commented on test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/DollarQueryTests.cs
> -    public class DollarQueryTests : WebApiTestBase<DollarQueryTests>
@xuzhg When working on the feature, a reviewer had requested for a test that verifies two things:
- that a request fails when the query options part of the URL exceeds a particular length, and
- that a request succeeds if you pass the same query options in the request body

That is what gave birth to the test in question. The challenge with `WebApiTestBase<T>` is that it makes use of `TestServer` and I couldn't figure out a way to impose request limits. Kestrel server on the other hand imposes the limits that make it possible to implement the requested test

That leaves us with the following options:
- get rid of the test altogether
- or, figure out a way to fail a request when the header violates configured limits when using `WebApiTestBase<T>`/`TestServer` - maybe we could use a middleware to achieve that?
- or, move this particular test to its own test class that derives from `WebHostTestBase<T>` class

2021-04-09 08:00 UTC, gathogojr commented on test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/DollarQueryTests.cs
> -
Apart from confirming a known fact - that web server impose limitations on the request header size - this test doesn't add more value so its justifiable to drop it

2021-04-09 08:01 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/ODataServiceCollectionExtensions.cs
> +                ServiceDescriptor.Singleton<IODataQueryRequestParser, DefaultODataQueryRequestParser>());
@xuzhg Okay to register as Singleton or would Transient be preferable?

2021-04-09 18:25 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/ODataServiceCollectionExtensions.cs
> +                ServiceDescriptor.Singleton<IODataQueryRequestParser, DefaultODataQueryRequestParser>());
I think it should be singleton.

---
In reply to: [610428027](https://github.com/OData/AspNetCoreOData/pull/121#discussion_r610428027) [](ancestors = 610428027)

2021-04-09 18:28 UTC, xuzhg commented on test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/DollarQueryTests.cs
> -
would you please share a link for that?

---
In reply to: [610427377](https://github.com/OData/AspNetCoreOData/pull/121#discussion_r610427377) [](ancestors = 610427377)

2021-04-09 18:28 UTC, xuzhg approved these changes
:shipit:

2021-04-09 18:29 UTC, xuzhg commented on test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
> -	public ODataQueryRequestMiddleware (Microsoft.AspNetCore.OData.Query.IODataQueryRequestParser queryRequestParser, Microsoft.AspNetCore.Http.RequestDelegate next)
>queryRequestParser [](start = 95, length = 18)

It's weird,  It works without updating .NET 5 public API baseline?

2021-04-09 18:30 UTC, merged

2021-04-09 18:45 UTC, gathogojr commented on test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/DollarQueryTests.cs
> -
> would you please share a link for that?
> 
> In reply to: [610427377](https://github.com/OData/AspNetCoreOData/pull/121#discussion_r610427377) [](ancestors = 610427377)

@xuzhg http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360953

2021-04-09 18:46 UTC, gathogojr commented on test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
> -	public ODataQueryRequestMiddleware (Microsoft.AspNetCore.OData.Query.IODataQueryRequestParser queryRequestParser, Microsoft.AspNetCore.Http.RequestDelegate next)
I updated the baseline for both .NET 3.1 and 5