Fix behaviour for Preflight requests on the ODataBatchMiddleware
OData/AspNetCoreOData pull request #187
Opened 2021-06-02 09:10 UTC by marabooy

2021-06-02 16:30 UTC, xuzhg requested changes

2021-06-02 16:30 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Batch/ODataBatchMiddleware.cs
> +            bool isPreFlight = HttpMethods.IsOptions(context.Request.Method);
From OData spec, 
`Batch requests are submitted as a single HTTP POST request to the batch endpoint of a service, located at the URL $batch relative to the service root.`

So, can we modify to allow "POST" HTTP method only? then we needn't compare "Options" HTTP method?

2021-06-03 08:00 UTC, habbes approved these changes

2021-09-15 17:04 UTC, xuzhg approved these changes

2021-09-16 07:08 UTC, merged