Redesign FilterBinder
OData/AspNetCoreOData pull request #291
Opened 2021-08-31 06:51 UTC by KenitoInc

2021-09-21 12:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull);
Should these be part of the interface or are they implementation details of the `Bind()` method?

2021-09-21 12:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        IQueryable Bind(FilterBinderContext context);
Also, how come we don't have an overload that takes and returns an `object` like on the `ISelectExpandBinder`?

2021-09-21 12:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +        new public virtual Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull)
Why is the `new` keyword use here?

2021-09-21 12:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +        new public virtual Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull)
I've just read from [the docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier) that it's used to hide a member inherited from the base class. In this case I assume you're hiding `CreateBinaryExpression` from `ExpressionBinderBase`. Out of curiosity, why not make the bass class method virtual since it seems that we're extending it here?

2021-09-21 12:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +        new public virtual Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull)
Also, since we're fowarding the arguments to the base class verbatim, why do we need to define that method here? Is the only thing we're adding the `Contract.Assert` statements?

2021-09-21 12:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +                        filterBinder.Model = context.Model;
Given that there was a TODO comment, maybe we should find it out why this statement was frowned upon and try to address it.

I assume `filterBinder` gets its `Model` from DI. Under which circumstances would that model be different from `context.Model`? If you remove the if statement, are there any tests that fail?

2021-09-21 14:25 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +                IFilterBinder binder = queryContext.GetFilterBinder(querySettings);
```suggestion
                IFilterBinder binder = queryContext.GetFilterBinder(querySettings);

                FilterBinderContext filterBinderContext = new FilterBinderContext()
                {
                    Source = null,
                    OrderByClause = orderbyClause,
                    QueryContext = queryContext,
                    QuerySettings = querySettings,
                    ElementClrType = elementType
                };
```

2021-09-21 14:25 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Query/ApplyQueryOptions.cs
> +                    FilterBinderContext filterBinderContext = new FilterBinderContext()
Move this closer to where it is used.

2021-09-21 14:25 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Query/FilterQueryOption.cs
> +            FilterBinderContext filterBinderContext = new FilterBinderContext()
Move variable closer to where it is used.

2021-09-22 08:29 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull);
There are other areas of the library that relies explicitly on the `CreateBinaryExpression(...)` method directly without using it via the `Bind(...)` method. see https://github.com/OData/AspNetCoreOData/blob/d63657f5f149ab66d1741b9d8af954c2fdb074fc/src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs#L307

2021-09-22 08:30 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull);
Therefore every implementation of the `IFilterBinder` need the `CreateBinaryExpression(...)` method

2021-09-22 08:33 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        IQueryable Bind(FilterBinderContext context);
I am not aware on any specific usecase where we need to return an `object`. Therefore, since we only have an `IQueryable` as a source input, we put the `IQueryable` in the `FilterBinderContext`;

2021-09-22 08:34 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +        new public virtual Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull)
See [this comment](https://github.com/OData/AspNetCoreOData/pull/291#discussion_r713712944)

2021-09-22 09:14 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +                        filterBinder.Model = context.Model;
I commented out the code and not test failed. Let me return the TODO comment.

2021-09-22 09:16 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +                IFilterBinder binder = queryContext.GetFilterBinder(querySettings);
#Resolved

2021-09-22 09:17 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Query/ApplyQueryOptions.cs
> +                    FilterBinderContext filterBinderContext = new FilterBinderContext()
#Resolved

2021-09-22 09:17 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Query/FilterQueryOption.cs
> +            FilterBinderContext filterBinderContext = new FilterBinderContext()
#Resolved

2021-09-23 18:40 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression CreateBinaryExpression(BinaryOperatorKind binaryOperator, Expression left, Expression right, bool liftToNull);
You can add an extension on "IFilterBinder" to provide such method.

2021-09-23 18:44 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression BindOrderByClause(FilterBinderContext context);
i don't think we should have these two APIs in the interface

2021-09-23 18:45 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        IQueryable Bind(FilterBinderContext context);
I'd like to move "IQueryable" to argument and name it as source.

2021-09-23 18:46 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        IQueryable Bind(FilterBinderContext context);
+1

2021-09-23 18:46 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            InternalAssembliesResolver = AssemblyResolverHelper.Default;
>InternalAssembliesResolver = AssemblyResolverHelper.Default; [](http://example.com/codeflow?start=12&length=60)

retrieve it from context.

2021-09-23 18:47 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            Contract.Assert(context.ElementClrType != null);
for public API, doesn't use Contract.Assert. If the input is not good, throw argument null exception.

2021-09-23 18:48 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            Contract.Assert(context.ElementClrType != null);
we should move it to FilterBinderContext.
It means if we get a null context, we get null "FilterClause" and Null "ElementClrType"

2021-10-01 09:13 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            return query;
```suggestion
            return ExpressionHelpers.Where(query, filterExpression, context.ElementClrType);
```

2021-10-01 09:13 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            return filter;
```suggestion
         return BindFilterClause(this, context.FilterClause, context.ElementClrType);
```

2021-10-01 09:13 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            return orderByExpression;
```suggestion
        return BindOrderByClause(this, context.OrderByClause, context.ElementClrType);
```

2021-10-01 09:13 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            if (node == null)
What does this imply? does this forbid count with no parameters?

2021-10-01 09:13 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinderContext.cs
> +{
Happy that we are removing the context from the main filter binder. 
😃

2021-10-01 09:13 UTC, marabooy commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +                FilterBinder filterBinder = binder as FilterBinder;
If we think the model may be something useful for the general case we could pull this up to the interface. Instead.

2021-10-01 09:13 UTC, marabooy commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/FilterBinderTests.cs
> +            ExceptionAssert.ThrowsArgumentNull(() => binder.Bind(node), "node");
```suggestion
            ExceptionAssert.ThrowsArgumentNull(() => binder.Bind(null), "node");
```

2021-10-01 18:25 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression BindOrderByClause(FilterBinderContext context);
Ping

2021-10-01 18:27 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            Contract.Assert(context.FilterClause != null);
in the public method, let's throw argument null exception.

2021-10-01 18:29 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression BindOrderByClause(IQueryable source, FilterBinderContext context);
It's better to have a OrderByBinder ? and OrderByBinderContext?

2021-10-01 18:29 UTC, xuzhg requested changes
:clock1:

2021-10-05 09:18 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            if (node == null)
It forbids a null `CountNode`

2021-10-05 09:40 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression BindOrderByClause(IQueryable source, FilterBinderContext context);
I have moved the `OrderByClause` binding to `OrderByBinder`

2021-11-01 18:43 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        LambdaExpression BindFilterClause(IQueryable source, FilterBinderContext context);
can we move it to Extension method for "IFilterBinder"?

2021-11-01 18:46 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
> +            builder.AddService<IFilterBinder, FilterBinder>(ServiceLifetime.Transient);
>Transient [](http://example.com/codeflow?start=76&length=9)

can we change to "Scoped"? do we have anything changed every time?

2021-11-01 18:48 UTC, xuzhg commented
It looks good but there's one more comment needed to resolve. Thanks.

2021-11-01 18:48 UTC, xuzhg approved these changes
:shipit:

2021-11-02 07:31 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        Expression BindOrderByClause(FilterBinderContext context);
#Resolved

2021-11-02 07:49 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
> +            builder.AddService<IFilterBinder, FilterBinder>(ServiceLifetime.Transient);
Done

2021-11-02 07:57 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        /// <returns>The new <see cref="IQueryable"/> after the filter query has been applied to.</returns>
```suggestion
        /// <returns>The new <see cref="IQueryable"/> after the filter query has been applied.</returns>
```

2021-11-02 07:57 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        /// Creates an <see cref="LambdaExpression"/> from an OData $filter parse tree represented by <see cref="FilterClause"/>.
```suggestion
        /// Creates a <see cref="LambdaExpression"/> from an OData $filter parse tree represented by <see cref="FilterClause"/>.
```

2021-11-02 07:58 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        /// <returns>An <see cref="LambdaExpression"/> which can be later applied to an <see cref="IQueryable"/>.</returns>
```suggestion
        /// <returns>A <see cref="LambdaExpression"/> which can be later applied to an <see cref="IQueryable"/>.</returns>
```

2021-11-02 08:08 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            if (collectionNode != null)
```suggestion
            if (node as CollectionNode collectionNode)
```

2021-11-02 08:08 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            else if (singleValueNode != null)
```suggestion
            else if (node as SingleValueNode singleValueNode)
```

2021-11-02 08:09 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        LambdaExpression BindFilterClause(IQueryable source, FilterBinderContext context);
Should this be part of the interface or is it an implementation detail?

2021-11-02 08:21 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            PropertyInfo prop = GetDynamicPropertyContainer(openNode);
```suggestion

            PropertyInfo prop = GetDynamicPropertyContainer(openNode);
```

2021-11-02 08:23 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        LambdaExpression BindFilterClause(IQueryable source, FilterBinderContext context);
How comes `IFilterBinder` has 2 methods and `IOrderByBinder` has only one method?
Also, why does the `Bind()` method in `IFilterBinder` return an `IQueryable` but the `IOrderByBinder` return `LambdaExpression`?
I think it would be a good idea to have some symmetry/consistency in the naming and function of these methods if possible. Or is this also a side-effect of the reliance on `ExpressionBinderBase`?

2021-11-02 08:24 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            return propertyAccessExpression;
```suggestion
            }
            
            return propertyAccessExpression;
```

2021-11-02 08:26 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            var source = Bind(openNode.Source);
You don't need a null check or that is handled in `Bind` method?

2021-11-02 08:27 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +    public class FilterOrderByBinderBase : ExpressionBinderBase
What's the rationale of combining the `Filter` and `OrderBy` binding in the same class?

2021-11-02 08:27 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +    /// an <see cref="Expression"/> and applies it to an <see cref="IQueryable"/>.
If this also takes of `$orderby`, consider mentioning it in the doc comments.

2021-11-02 08:30 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            _lambdaParameters.Add(rangeVariable.Name, filterParameter);
```suggestion
            _lambdaParameters = new Dictionary<string, ParameterExpression>{ { rangeVariable.Name, filterParameter } };
```

2021-11-02 08:45 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +        /// Binds a <see cref="SingleResourceFunctionCallNode"/> to create a LINQ <see cref="Expression"/> that
You could add something about cast to the documentation for this method to disambiguate it from the one above.

2021-11-02 09:24 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            : base(settings, assembliesResolver, model)
The idea behind switching the positions of the `model` and `settings` agruments?

2021-11-02 12:18 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +        /// Gets the <see cref="ISelectExpandBinder"/>.
```suggestion
        /// Gets the <see cref="IOrderByBinder"/>.
```

2021-11-02 12:18 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +        /// <returns>The built <see cref="ISelectExpandBinder"/>.</returns>
```suggestion
        /// <returns>The built <see cref="IOrderByBinder"/>.</returns>
```

2021-11-02 12:20 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +            return binder ?? new OrderByBinder(querySettings, AssemblyResolverHelper.Default, context.Model);
Should you be using `AssemblyResolverHelper.Default` here or `GetAssemblyResolver(context)`?

2021-11-02 12:21 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
>              return binder ?? new FilterBinder(querySettings, AssemblyResolverHelper.Default, context.Model);
Should you be using `AssemblyResolverHelper.Default` here or `GetAssemblyResolver(context)`?

2021-11-02 12:22 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
> +            : base(settings, assembliesResolver, model)
Reverted this change

2021-11-02 12:30 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +        /// Binds a <see cref="SingleResourceFunctionCallNode"/> to create a LINQ <see cref="Expression"/> that
Done

2021-11-02 12:35 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            var source = Bind(openNode.Source);
Null check is done in the Bind(QueryNode node)

2021-11-02 12:36 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +    /// an <see cref="Expression"/> and applies it to an <see cref="IQueryable"/>.
I have edited the docs

2021-11-02 12:37 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +    public class FilterOrderByBinderBase : ExpressionBinderBase
`FilterOrderByBinderBase` is a base class for both `FilterBinder` and `OrderByBinder` since they share most of the methods used is generating expressions.

2021-11-02 12:51 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +        internal FilterOrderByBinderBase(IServiceProvider requestContainer)
```suggestion
        internal Type _filterType;
        
        internal FilterOrderByBinderBase(IServiceProvider requestContainer)
```

2021-11-02 12:51 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +        internal FilterOrderByBinderBase(IEdmModel model, IAssemblyResolver assembliesResolver, ODataQuerySettings settings)
```suggestion
        }
        
        internal FilterOrderByBinderBase(IEdmModel model, IAssemblyResolver assembliesResolver, ODataQuerySettings settings)
```

2021-11-02 12:59 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
>              return binder ?? new FilterBinder(querySettings, AssemblyResolverHelper.Default, context.Model);
Good catch.
Should be `context.GetAssemblyResolver()` since it's an extension method

2021-11-02 13:15 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IOrderByBinder.cs
> +        LambdaExpression Bind(IQueryable source, OrderByBinderContext context);
I have updated the methods.
We have a method with an IQueryable input and IQueryable output.
The method to output a LambdaExpression doesn't have an input since it generates an expression from the orderbyclause

2021-11-02 13:16 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IOrderByBinder.cs
> +        LambdaExpression Bind(IQueryable source, OrderByBinderContext context);
I have updated the methods

2021-11-02 13:19 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        LambdaExpression BindFilterClause(IQueryable source, FilterBinderContext context);
@habbes I have updated both interfaces and they have similar methods.

@xuzhg  @habbes `BindFilterClause` is also called independently from the `SelectExpandBinder`. Therefore am leaving it there since a customer might want to provide a custom implementation for it.
Moving `BindFilterClause` to an extension method will restrict those who would want to provide a custom implementation.

2021-11-04 07:57 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/OrderByBinder.cs
> +        internal LambdaExpression BindOrderByClause(OrderByClause orderBy, Type elementType)
Internal method could do with some documentation

2021-11-04 07:58 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/OrderByBinder.cs
> +        internal IQueryable BindOrderByClause(IQueryable source, OrderByClause orderBy, Type elementType, bool alreadyOrdered = false)
Internal method could do with some documentation

2021-11-04 08:14 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +            // TODO: bug in uri parser is causing this property to be null for the root property.
Can you create an issue to track or fix this?

2021-11-04 08:15 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/FilterOrderByBinderBase.cs
> +        private Expression BindCastSourceNode(QueryNode sourceNode)
The convention has been to have `private` methods appear after `public` and `internal`

2021-11-05 14:17 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/OrderByBinder.cs
> +        internal LambdaExpression BindOrderByClause(OrderByClause orderBy, Type elementType)
Done

2021-11-05 14:17 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/OrderByBinder.cs
> +        internal IQueryable BindOrderByClause(IQueryable source, OrderByClause orderBy, Type elementType, bool alreadyOrdered = false)
Done

2021-11-08 17:47 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/IFilterBinder.cs
> +        LambdaExpression Bind(Expression expression, FilterBinderContext context);
>LambdaExpression [](http://example.com/codeflow?start=8&length=16)

returns Expression directly?

2021-11-24 17:36 UTC, KenitoInc commented
Closing this PR since the diff (with others changes) are merged here https://github.com/OData/AspNetCoreOData/commit/6ff70818a2b85f0ec28e7834f2983c79cd19e330

2021-11-24 17:36 UTC, closed without merging