Redesign SelectExpandBinder to allow customizations
OData/AspNetCoreOData pull request #296
Opened 2021-09-03 09:15 UTC by KenitoInc

2021-09-09 12:59 UTC, odero commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        Expression GetProjectionLambda(SelectExpandQueryOption selectExpandQuery);
It seems existing implementations are returning `LambdaExpression` and the name of the method also implies returning a Lambda. Why not have the return type be a `LambdaExpression`?

2021-09-09 13:00 UTC, odero commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        /// <returns>The new <see cref="object"/> after the select/expand query has been applied to.</returns>
```suggestion
        /// <returns>The new <see cref="object"/> after the select/expand query has been applied.</returns>
```

2021-09-13 05:51 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        Expression GetProjectionLambda(SelectExpandQueryOption selectExpandQuery);
There is not specific reason I am returning `Expression`. I just decided to return the `Expression` since it's easy to cast it to a `LambdaExpression`

2021-09-13 05:53 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> -        public static IQueryable Bind(IQueryable queryable, ODataQuerySettings settings, SelectExpandQueryOption selectExpandQuery)
Exactly

2021-09-13 05:54 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        /// <returns>The new <see cref="object"/> after the select/expand query has been applied to.</returns>
#Resolved

2021-09-15 09:27 UTC, FlaviusHouk commented on src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
>              builder.AddService<FilterBinder>(ServiceLifetime.Transient);
While interface is added to SelectExpandBinder, wouldn't it be consistent to add interface for FilterBinder also?

2021-09-15 09:31 UTC, FlaviusHouk commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        Expression GetProjectionLambda(SelectExpandQueryOption selectExpandQuery);
But in general it will allow to implementers to return not ```LambdaExpression```. It is against Liskov Substitution Principle, but should be fortified by interface definition? Because now name of the method and return type is slightly confusing.

2021-09-15 09:34 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
>              builder.AddService<FilterBinder>(ServiceLifetime.Transient);
@FlaviusHouk We have a PR related to the FilterBinder #291

2021-09-15 09:35 UTC, FlaviusHouk commented on src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
>              builder.AddService<FilterBinder>(ServiceLifetime.Transient);
@KenitoInc thank you for pointing.

2021-09-15 12:11 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        Expression GetProjectionLambda(SelectExpandQueryOption selectExpandQuery);
#Resolved

2021-09-15 12:43 UTC, odero approved these changes
lgtm

2021-09-16 13:38 UTC, habbes requested changes

2021-09-16 13:38 UTC, habbes commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +            SelectExpandBinder binder = new SelectExpandBinder(_settings, selectExpand.Context);
If these arguments are passed to the `Bind()` method via the `selectExpandBinderContext`, why do you need to also pass them to the constructor?

2021-09-16 13:38 UTC, habbes commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +                QueryContext = selectExpand.Context
Is it necessary to set `QueryContext` as separate property if it can be retrieved from `selectExpand.Context`? Are there cases where these two are not the same? Or cases where `selectExpand.Context` is not defined?

2021-09-16 13:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +            _settings = context.QuerySettings;
I think it's potentially a problem that we modify the private variables, i.e. the state of the object, whenever `Bind()` is called. In the pre-existing implementation, the static method `SelectExpandBinder.Bind()` creates a new instance of `SelectExpandBinder` each time.

However, with this change, we're registering a single instance of `SelectExpandBinder` as a singleton, this means modifying the state is inherently not thread safe.

If we have two concurrent requests and each one calls `Bind()` one can modify the context that was set by the other request before it finished executing, leading to sporadic, hard-to-debug and hard-to-reproduce errors (we've already faced a few of those due to using writeable/stateful objects as singletons that are modified by different requests concurrently, [see this for example](https://github.com/OData/odata.net/issues/2057)).

I think the best way to avoid such issues is to get rid of this private fields altogether, unless they're read-only and only set in the constructor. It's safer to just pass the context object down to every method that needs it.

2021-09-16 13:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +            Contract.Assert(context.QuerySettings.HandleNullPropagation != HandleNullPropagationOption.Default);
I see it also exists in the old code. Still not sure what it's meant to achieve.

2021-09-16 13:38 UTC, habbes commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        LambdaExpression GetProjectionLambda(SelectExpandQueryOption selectExpandQuery);
It seems that in the current code `GetProjectionLambda` is private, that means that it's not being called by any other classes. So we can safely assume that not making it public will not cause any issues.

I propose we remove it from the interface. Since the customer is already going to implement the `Bind()` methods, which is what we care about, then we shouldn't care whether they implement `GetProjectLambda` or use a different approach.

But if we want to make it easier for them to re-use the same logic for both `Bind()` methods, and take advantage of lambda expressions in both-cases, then I think that's already taken care of by the fact that you made `GetProjectionLambda` public and virtual in the default implementation. I think it make sense to keep it there, but not on the interface.

2021-09-17 06:57 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +            Contract.Assert(context.QuerySettings.HandleNullPropagation != HandleNullPropagationOption.Default);
The assert ensures those properties are not null.

2021-09-17 06:59 UTC, KenitoInc commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +            SelectExpandBinder binder = new SelectExpandBinder(_settings, selectExpand.Context);
That constructor is `internal`. It's used for testing purposes only. We can clean that though

2021-09-17 10:48 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
> +        LambdaExpression GetProjectionLambda(SelectExpandQueryOption selectExpandQuery);
#Resolved

2021-09-17 10:48 UTC, KenitoInc commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +            SelectExpandBinder binder = new SelectExpandBinder(_settings, selectExpand.Context);
#Resolved

2021-09-17 10:48 UTC, KenitoInc commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +                QueryContext = selectExpand.Context
#Resolved

2021-09-17 10:48 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +            _settings = context.QuerySettings;
#Resolved

2021-09-17 11:06 UTC, habbes approved these changes

2021-09-17 13:11 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +            Contract.Assert(context.QuerySettings.HandleNullPropagation != HandleNullPropagationOption.Default);
I think we should be using debug asserts here rather than contract asserts

2021-09-17 13:32 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +        public virtual LambdaExpression GetProjectionLambda(SelectExpandBinderContext context)
Would there be any harm in making this method protected?

2021-09-17 13:37 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +        private Expression BuildPropertyContainer(Expression source, SelectExpandBinderContext context,
nit: In other methods where you have made similar changes, you added `SelectExpandBinderContext context` as the first parameter

2021-09-17 13:42 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +                querySettings = EdmHelpers.GetModelBoundQuerySettings(structuralProperty, propertyStructuredType, model);
Take note of [this PR](https://github.com/OData/AspNetCoreOData/pull/306) where `GetModelBoundQuerySettings` has been converted into an extension method. If you merge your PR after, you made need to rebase and refactor your code

2021-09-17 13:45 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +            }
You could replace this with:
```csharp
ISelectExpandBinder binder = context.RequestContainer?.GetService<ISelectExpandBinder>();
```

2021-09-17 13:46 UTC, gathogojr approved these changes
Left some comments otherwise LGTM

2021-09-17 14:38 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
> +            }
Done

2021-09-17 14:38 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +        private Expression BuildPropertyContainer(Expression source, SelectExpandBinderContext context,
Done

2021-09-17 14:38 UTC, KenitoInc commented on src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
> +        public virtual LambdaExpression GetProjectionLambda(SelectExpandBinderContext context)
I have changed it to protected

2021-09-17 15:19 UTC, merged