Changed CreatedODataResult and UpdatedODataResult to inherit from Action result
OData/AspNetCoreOData pull request #33
Opened 2020-11-11 14:12 UTC by weitzhandler

Fixes #17.

2020-11-11 22:12 UTC, julealgon requested changes

2020-11-11 22:12 UTC, julealgon commented on src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs
> +    public class CreatedODataResult<T> : ActionResult, IConvertToActionResult
I believe implementing `IConvertToActionResult` is not needed here. This is implemented by `ActionResult<T>` and it already handles anything that inherits from the base `ActionResult` class.

If you check all other native result classes (like `OkObjectResult`, `OkCreatedResult`, etc) they all inherit from `ActionResult`, and do _not_  implement `IConvertToActionResult`.

Would recommend double checking and dropping this implementation.

2020-11-11 22:12 UTC, julealgon commented on src/Microsoft.AspNetCore.OData/Results/UpdatedODataResult.cs
> +    public class UpdatedODataResult<T> : ActionResult, IConvertToActionResult
Same as above. Implementing `IConvertToActionResult` shouldn't be needed (it might even be a semantic mistake since this already implements `IActionResult` so it is already convertible to it).

2020-11-11 22:12 UTC, julealgon commented
Thanks again for taking this up, much appreciated.

2020-11-11 23:32 UTC, weitzhandler commented on src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs
> +    public class CreatedODataResult<T> : ActionResult, IConvertToActionResult
You're right.

2020-11-12 14:47 UTC, julealgon approved these changes

2020-12-17 01:31 UTC, xuzhg commented
Merged https://github.com/OData/AspNetCoreOData/commit/faf5a6455c1b62560ec563d7a4d3fbec0a5e2c2c

2020-12-17 01:31 UTC, closed without merging