Support DateOnly and TimeOnly
OData/AspNetCoreOData pull request #450
Opened 2022-01-20 03:18 UTC by xuzhg

#413 

Support DateOnly & TimeOnly new types defined in .NET 6.

1) Add the .NET 6.0 target framework to introduce new types (DateOnly and TimeOnly)
2) Support serialize of DateOnly & TimeOnly as "Date" and "TimeOfDay"
3) Support deserialize of DateOnly & TimeOnly from "Date" and "TimeOfDay".
4) Support the query option on DateOnly & TimeOnly, for example $filter.

2022-01-20 19:04 UTC, julealgon requested changes

2022-01-20 19:04 UTC, julealgon commented on src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs
> +        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>")]
Also missing justification (and also apparently unrelated to the changes).

2022-01-20 19:04 UTC, julealgon commented on test/Microsoft.AspNetCore.OData.E2E.Tests/Microsoft.AspNetCore.OData.E2E.Tests.csproj
> +  </ItemGroup>
Considering none of the changes related to `TimeOnly` and `DateOnly` have any relationship to EF (I'm assuming this), do we really need to do this?

2022-01-20 19:06 UTC, julealgon commented
You might also want to add a comment to the description to hard link this PR with #413.

2022-01-20 19:22 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Edm/DefaultODataTypeMapper.cs
> +            BuildTypeMapping<DateOnly?>(EdmPrimitiveTypeKind.Date, isStandard: false);
Would you mind sharing with me a contribution for this? I'd love to take and merge it for you.

2022-01-20 19:23 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.SingleValueFunctionCall.cs
> +            else if (ExpressionBinderHelper.IsType<DateOnly>(parameter.Type))
:) I have the same concern.

2022-01-20 19:27 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs
> +        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>")]
.NET 6 introduces a new overload for Append and raises a compile waring to use the old overload.

So, before .NET 6, it's ok to build without a warning. however, there's a build warning after add .NET 6 target framework.

Since I have to add .NET 6 target framework to introduce DateOnly and TimeOnly type, so, a build warning raises.

Originally, i use 
#if NET6_0
   // call new overload
#else
  // call old overload
#endif

But, i think it's easy to suppress the message since that's only for debugging purposes.  Thoughts?

2022-01-20 19:38 UTC, julealgon commented on src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs
> +        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>")]
> .NET 6 introduces a new overload for Append and raises a compile waring to use the old overload.

Ah I see, so that's why it is only raised now. Gotcha.

> Originally, i use
#if NET6_0
// call new overload
#else
// call old overload
#endif
>
> But, i think it's easy to suppress the message since that's only for debugging purposes. Thoughts?

I'd agree. The docs for this rule state:
> It is safe to suppress a warning from this rule when it is certain that the default format is the correct choice, and where code maintainability is not an important development priority.

I LOL'd at the second part ("nah, this doesn't need to be maintainable" 🤣 ) but the first part says that if you are ok with the defaults it is a safe suppression.

Just make sure to replace the `"<Pending>"` there with a simple explanation, maybe like "The default format provider is fine here." or something.

2022-01-20 19:39 UTC, julealgon commented on src/Microsoft.AspNetCore.OData/Edm/DefaultODataTypeMapper.cs
> +            BuildTypeMapping<DateOnly?>(EdmPrimitiveTypeKind.Date, isStandard: false);
For sure. I'll wait until you merge this and then refactor the whole block so as to avoid you having to rebase it.

2022-01-20 19:50 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs
> +        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>")]
Took your suggestion. Thanks.

2022-01-20 19:52 UTC, xuzhg commented
I already added the link between issue and pr. did i miss something?

---
In reply to: [1017831541](https://github.com/OData/AspNetCoreOData/pull/450#issuecomment-1017831541) [](http://example.com/codeflow?ancestors=1017831541,1017831541)

2022-01-20 19:55 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
> +#if NET6_0
Since there's only two new methods added, i'd like to create a new file until we have more .NET 6 specify methods added.  Thanks for your suggestion.

2022-01-20 19:59 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Edm/DefaultODataTypeMapper.cs
> +            BuildTypeMapping<DateOnly?>(EdmPrimitiveTypeKind.Date, isStandard: false);
Yes, you are right for the order. I forget what i said. OMG

2022-01-21 01:31 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/ClrCanonicalFunctions.cs
> +        }.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
I changed to use {}.

2022-01-21 01:34 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderHelper.cs
> +            long ticksPerSecond = 10000000L;
Yes, that's just what i am looking for.

2022-01-21 01:35 UTC, xuzhg commented on test/Microsoft.AspNetCore.OData.E2E.Tests/Microsoft.AspNetCore.OData.E2E.Tests.csproj
> +  </ItemGroup>
Also, i think it's ok to add them since I added .NET 5 target framework, and make sure the test running under .NET 6 runtime using the 6.0 EF core nuget.

2022-01-21 01:38 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Edm/EdmPrimitiveHelper.cs
> +                else if (type == typeof(DateOnly))
Thanks for the suggestion, i'd like to leave for other PR.

2022-01-21 01:42 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Edm/EdmPrimitiveHelper.cs
> +                        return new TimeOnly(tod.Hours, tod.Minutes, tod.Seconds, (int)tod.Milliseconds);
Yep, It's ODL problem and now i have to cast it.

2022-01-21 07:37 UTC, merged