Adding support for case insensitive action names
OData/AspNetCoreOData pull request #519
Opened 2022-03-10 23:21 UTC by giulianob

I am working with an API which uses camel case OData action names but these are not found because the routing is case sensitive. For example, the following will not work:
```diff
// sample/ODataCustomizedSample/Models/EnumsEdmModel.cs:75
- var actionConfiguration = employee.Action("AddSkill");
+ var actionConfiguration = employee.Action("addSkill");
```
This fails because `OperationRoutingConvension` is case sensitive. Changing the following makes it work.
```diff
// src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs:91
- IEnumerable<IEdmOperation> candidates = context.Model.SchemaElements.OfType<IEdmOperation>().Where(f => f.IsBound && f.Name == operationName);
+ IEnumerable<IEdmOperation> candidates = context.Model.SchemaElements.OfType<IEdmOperation>().Where(f => f.IsBound && string.Equals(f.Name, operationName, StringComparison.InvariantCultureIgnoreCase));
```

I have introduced the property `EnableActionNameCaseInsensitive` to optionally enable case insensitive action names.

2022-03-11 01:37 UTC, corranrogue9 commented
@giulianob , thanks for the contribution! Did you file an issue for this? I'm pretty happy with the change, but it looks like the update to the API is causing a test failure. Can you take a look at that?

2022-03-11 22:06 UTC, giulianob commented
@corranrogue9 Updated the API definitions. Do you want me to create an issue? I ran into the issue and created the PR.

2022-03-14 17:06 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs
> +            };
why don't you use " ? : ", it seems more clear

2022-03-14 17:07 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs
> +            };
why do we only apply the configuration on in operation routing convention? not in other conventions?

2022-03-14 17:08 UTC, xuzhg commented on test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/ActionRoutingConventionTests.cs
> +        private readonly ITestOutputHelper _testOutputHelper;
>_testOutputHelper [](http://example.com/codeflow?start=43&length=17)

It seems there's no place using this output?

2022-03-14 17:08 UTC, xuzhg requested changes
:clock1:

2022-03-14 21:12 UTC, giulianob commented on src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs
> +            };
I went through the conventions and made them case insensitive. Thanks!

2022-03-14 21:12 UTC, giulianob commented on test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/ActionRoutingConventionTests.cs
> +        private readonly ITestOutputHelper _testOutputHelper;
Fixed

2022-03-14 21:12 UTC, giulianob commented on src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs
> +            };
Changed

2022-03-16 00:26 UTC, giulianob commented
@xuzhg I resolved all of your comments. Thanks for the review.

2022-03-16 05:58 UTC, xuzhg approved these changes

2022-03-16 05:58 UTC, merged