Get value of property with data member consideration
OData/AspNetCoreOData pull request #647
Opened 2022-07-25 22:50 UTC by thanhtruongmsft

### Issues

The `propertyName` parameter in the function `GetPropertyAccessLambda` is DataMember name and it was not the actual property name. It caused the issue `Expression.Property(odataItParameter, propertyName);` was crashed.

### Description

The change is to find the actual property name and get its value from the object.

2022-08-05 17:37 UTC, xuzhg requested changes

2022-08-05 17:37 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Query/ExpressionHelpers.cs
> -            MemberExpression propertyAccess = Expression.Property(odataItParameter, propertyName);
That's weird, because if you use OData model builder, the DataMember is considered in the Edm model.

So, You don't need to find any attributes. You can call "GetClrPropertyName" on the model to get the actual CLR property name. at: https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Edm/EdmModelAnnotationExtensions.cs#L166

So, my suggestion is 
1) Leave GetPropertyAccessLambda unchanged, we assume the propertyName coming is correct
2) at the upper layer (where calling this method), we can use the model and the IEdmProperty to get the actual CRL property name.

2022-08-05 23:03 UTC, ttruatl commented
@xuzhg have you had a chance to look at the related issue [#2443](https://github.com/OData/WebApi/issues/2443)?

2022-08-12 06:38 UTC, xuzhg commented
> @xuzhg have you had a chance to look at the related issue [#2443](https://github.com/OData/WebApi/issues/2443)?

What do you mean? 

My suggestion is to call 'GetClrPropertyName' before calling into this method to get the real property name? Are you using non-Edm scenario?

2023-02-09 05:24 UTC, KenitoInc commented
@ttruatl 
I have fixed the code as per @xuzhg suggestion.
Kindly add tests

2023-06-30 13:09 UTC, KenitoInc commented
@microsoft-github-policy-service agree

2023-06-30 14:22 UTC, KenitoInc commented
@ttruatl 
I have added tests.
KIndly fix the CLA agreement so that we can resolve this PR

2023-07-03 04:52 UTC, gathogojr commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +    }
nit:
```suggestion
    }

```

2023-07-03 04:55 UTC, gathogojr commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +            Assert.NotNull(queryable);
Is this assertion really sufficient?

2023-07-04 13:57 UTC, KenitoInc commented on test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs
> +            Assert.NotNull(queryable);
I have updated tests

2023-07-05 12:12 UTC, KenitoInc commented
Resolved by #980

2023-07-05 12:12 UTC, closed without merging