fixes issue 727 [JsonIgnore] attribute ignored when using $expand
OData/AspNetCoreOData pull request #728
Opened 2022-10-27 03:01 UTC by mattperdeck

Fixes https://github.com/OData/AspNetCoreOData/issues/727

**Cause of the bug**

I found that when using $expand, the MapProperty methods of the default implementations for IPropertyMapper (for System.Text.Json and Newtonsoft.Json) contain code to interpret attributes applied to fields in the view model on their own. That is, they do not rely on the standard libraries to serialise the object, apply attributes, etc. 

Also, the only attribute they support is the property to rename a field - JsonProperty for Newtonsoft.Json, JsonPropertyName for System.Text.Json. Every other attribute would be ignored, including JsonIgnore. This explains why the bug is happening.

**Solution in this pull request**

1. Updated the MapProperty methods, so they check whether the field has the JsonIgnore attribute, and if so, return null (to indicate to ignore the field).
2. Updated the ToDictionary.... methods calling MapProperty so they no longer throw when MapProperty returns null. Instead, they simply do not add the field to the dictionairy. Also updated comments and error messages to reflect this change in the contract of the MapProperty method.
3. Updated affected unit tests, making sure that the new contract for MapProperty etc. is tested properly. Added unit tests for Newtonsoft Json version of MapProperty.

2022-11-01 17:15 UTC, corranrogue9 commented on src/Microsoft.AspNetCore.OData.NewtonsoftJson/JsonPropertyNameMapper.cs
> +            JsonIgnoreAttribute jsonIgnore = GetJsonIgnore(info);
Is this really the direction we want to go? Are we planning to support *all* `System.Text.Json` attributes?

2022-11-01 17:15 UTC, corranrogue9 commented on src/Microsoft.AspNetCore.OData.NewtonsoftJson/JsonPropertyNameMapper.cs
> +            JsonIgnoreAttribute jsonIgnore = GetJsonIgnore(info);
@xuzhg  @mikepizzo

2022-11-01 17:15 UTC, corranrogue9 requested changes
We need to decide our policy on which attributes we are supporting

2022-12-09 17:26 UTC, xuzhg approved these changes

2022-12-09 17:35 UTC, merged