Enable declared Untyped and undeclared Untyped
OData/AspNetCoreOData pull request #904
Opened 2023-05-02 18:05 UTC by xuzhg

1. Can read declared Untyped and undeclared Untyped, include collection
2. Can write declared Untyped and undeclared Untyped, include collection

2023-05-11 23:33 UTC, mikepizzo commented on sample/ODataRoutingSample/Controllers/PeopleController.cs
> +            //};
are these commented lines things that are not supported today but should be supported in the future, or things that are supported but not part of this test, or?

2023-05-11 23:34 UTC, mikepizzo commented on sample/ODataRoutingSample/Controllers/PeopleController.cs
> +                // So far, it can't support it?
are untyped collections supported with this PR (but not collections of structured types?)

2023-05-11 23:36 UTC, mikepizzo commented on sample/ODataRoutingSample/Models/Person.cs
> +        public AwsCondition Condition { get; set; }
>AwsCondition [](http://example.com/codeflow?start=15&length=12)

Use a more generic name (maybe something like CustomProperties?) in the public sample.

2023-05-11 23:37 UTC, mikepizzo commented on sample/ODataRoutingSample/Models/Person.cs
> +        public IList<object> Sources { get; set; } // Collection(Edm.Untyped)
why do we need two untyped properties and two untyped collection properties?

2023-05-11 23:40 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
> +            // Do we need conside IDictionary interface? ==> No, let's skip it.
>conside [](http://example.com/codeflow?start=26&length=7)

typo: "consider"

2023-05-11 23:42 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
> +        internal static bool IsDictionary(Type clrType, out Type keyType, out Type valueType)
>IsDictionary [](http://example.com/codeflow?start=29&length=12)

This method is going to be expensive -- we need to be careful where we use it, and might consider caching the result if this is called repeatedly for the same type.

2023-05-11 23:44 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
> +                             && t.GetGenericTypeDefinition() == typeof(IDictionary<,>));
consider rewriting this logic without relying on LINQ for better performance.

2023-05-12 00:11 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Edm/EdmHelpers.cs
> +            }
better would be either:

if (edmTypeReference is IEdmStructuredTypeReference structuredTypeReference)
{
    return structuredTypeReference;
}

or, if you can use that (requires C# 7), you can do:

IEdmStructuredTypeReference structuredTypeReference = edmTypeReference as IEdmStructuredTypeReference;
if(structuredTypeReference != null)
{
   return structuredTypeReference
}

either one will avoid the redundant type check.

2023-05-12 15:14 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
> +                nestedReadContext.ResourceType = typeof(EdmUntypedObject);
>typeof(EdmUntypedObject) [](http://example.com/codeflow?start=49&length=24)

should we have a static for this to return the same instance of typeof(EdmUntypedObject), rather than call typeof() each time?

2023-05-12 15:16 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
> +                //
>// [](http://example.com/codeflow?start=16&length=2)

did you intend to add a comment here?

2023-05-12 15:21 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceSetDeserializer.cs
> +            if (setItemElementType.IsUntyped())
>setItemElementType [](http://example.com/codeflow?start=16&length=18)

should this be setItemElementType or structuredType?

2023-05-12 15:58 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +                    if (nestedResourceInfo != null)
>nestedResourceInfo [](http://example.com/codeflow?start=24&length=18)

when would this be null?

2023-05-12 16:00 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +        private async Task WriteUntypedPropertiesAsync(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
>WriteUntypedPropertiesAsync [](http://example.com/codeflow?start=27&length=27)

so untyped properties are written after typed primitive properties? why don't we just write them as we come across them?

2023-05-12 16:06 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +            // This's the workaround and when ODL fixes the issue, we should remove these codes.
>     // This's the workaround and when ODL fixes the issue, we should remove these codes. [](http://example.com/codeflow?start=7&length=89)

do we have an ODL issue logged for this? maybe put a reference to it here for tracking.

2023-05-12 16:12 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
> +        internal IEdmTypeReference TryGetEdmType(object instance, Type type)
>TryGetEdmType [](http://example.com/codeflow?start=35&length=13)

the name of this makes me think it will return null if it can't get an enum type, so everywhere it's used I ask myself "what if it's null?  However, I think it's intended to *always* return an EdmType or an untyped value, so maybe name something like GetEdmTypeOrUntyped?

2023-05-12 16:17 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +            }
should we just check itemEdmType != null once and then nest the other checks within the if itemEdmTYpe != null?

2023-05-12 16:22 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +                    // Once ODL supports, let's call the correct writing methods.
>                  // Once ODL supports, let's call the correct writing methods. [](http://example.com/codeflow?start=2&length=79)

Can we create an issue in ODL and link it here?

2023-05-12 16:23 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +            IODataEdmTypeSerializer resourceSetSerializer = SerializerProvider.GetEdmTypeSerializer(itemSetType);
>itemSetType [](http://example.com/codeflow?start=100&length=11)

what if itemSetType is null? do we need a null check or assert?

2023-05-12 16:24 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +            IODataEdmTypeSerializer resourceSerializer = SerializerProvider.GetEdmTypeSerializer(resourceType);
>resourceType [](http://example.com/codeflow?start=97&length=12)

what if resourceType is null?

2023-05-12 16:30 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/SelectExpandNode.cs
> +                // TODO: Do we support the query option on property whose type is 'Edm.Untyped' or 'Collection(Edm.Untyped)'?
protocol supports this. also supports querying on dynamic properties of open types.  our support for declared untyped should be the same as for dynamic.

2023-05-12 16:37 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Routing/ODataPathExtensions.cs
> +            // TODO: do we need take the type cast into consideration?
>// TODO: do we need take the type cast into consideration? [](http://example.com/codeflow?start=12&length=58)

unless the type cast types to Edm.Untyped, the presence of the type cast should indicate that it's not untyped.

2023-05-12 16:48 UTC, mikepizzo requested changes
:clock1:

2023-05-12 17:14 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/IUntypedResourceMapper.cs
> +                    return null;
Great catch.

2023-05-12 17:15 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Value/EdmObjectExtensions.cs
> +using Microsoft.Spatial;
Removed

2023-05-12 17:17 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Routing/ODataPathExtensions.cs
> +            // TODO: do we need take the type cast into consideration?
Thanks for inputs.

2023-05-12 17:23 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +                    // Once ODL supports, let's call the correct writing methods.
[https://github.com/OData/odata.net/issues/2659](https://github.com/OData/odata.net/issues/2659)

2023-05-12 17:24 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +            IODataEdmTypeSerializer resourceSerializer = SerializerProvider.GetEdmTypeSerializer(resourceType);
basically, it's protected method, we can guarantee the input is not null. But, I can add a check to make sure it's valid.

2023-05-12 17:29 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceSetDeserializer.cs
> +            if (setItemElementType.IsUntyped())
should be use 'setItemElementType'

2023-05-12 17:33 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +            // This's the workaround and when ODL fixes the issue, we should remove these codes.
ODL fixed it using this PR:
[https://github.com/OData/odata.net/pull/2664](https://github.com/OData/odata.net/pull/2664)

2023-05-12 17:51 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
> +        internal static bool IsDictionary(Type clrType, out Type keyType, out Type valueType)
The test 'clrType' could be lots of it. If we cache it, it could be huge. And This test could be fast and only for untyped scenario, so, i think we don't need to cache it.

2023-05-12 17:51 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
> +                             && t.GetGenericTypeDefinition() == typeof(IDictionary<,>));
Rewrote it.

2023-05-12 17:54 UTC, xuzhg commented on sample/ODataRoutingSample/Models/Person.cs
> +        public AwsCondition Condition { get; set; }
Renamed.

2023-05-12 18:01 UTC, xuzhg commented on sample/ODataRoutingSample/Models/Person.cs
> +        public IList<object> Sources { get; set; } // Collection(Edm.Untyped)
One set for 'reading' from payload and writing them again in the response.

the other set is only 'setting' the value in the controller, and writing them in the response.

2023-05-12 18:07 UTC, xuzhg commented on sample/ODataRoutingSample/Controllers/PeopleController.cs
> +            //};
No, Here lists the different values that customer can assign to 'object' to represent a resource. I updated with comments in the code.

2023-05-12 18:08 UTC, xuzhg commented on sample/ODataRoutingSample/Controllers/PeopleController.cs
> +                // So far, it can't support it?
A resource in a nested collection of a 'untyped' collection doesn't support.  See [https://github.com/OData/odata.net/issues/2661](https://github.com/OData/odata.net/issues/2661). And I want to fix it soon with ODL.

2023-05-12 18:09 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
> +                nestedReadContext.ResourceType = typeof(EdmUntypedObject);
typeof() is a compile behavior, so,The typeof is an operator keyword which is used to get a type at the compile-time. So, it's ok here to use typeof.

2023-05-12 18:14 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +        private async Task WriteUntypedPropertiesAsync(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
We don't know how to write the untyped properties until we know the real type of the property value.
And it goes to different writing process based on the type kind. For example, if the real property value is a primitive, enum or collection of them, we should create a 'ODataProperty' and save it into the 'ODataResource.Properties'.

if the real property value is a collection of resource, or resource, it goes to write using nested resource info.

I don't want to pollute the 'non-untyped' writing process, So, keep untyped in its own writing method.

2023-05-12 18:17 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +                        continue;
Addressed in another review comments. In a summary, 
We don't know the real type of the untyped property value until we get the value. And different type goes to different writing logic. it's primitive, or it's nested resource info? 

So, same as the 'Stream' property, use its own logic to write.

2023-05-12 18:22 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerProvider.cs
> +                            (IEdmTypeReference)EdmUntypedStructuredTypeReference.NullableTypeReference);
Created.

2023-05-12 18:31 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
> +            }
refactored, please take a look again.

2023-05-12 19:16 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
> +        internal static bool IsDictionary(Type clrType, out Type keyType, out Type valueType)
I raised the concern because the code uses reflection, which is a concern for performance-critical code.

2023-05-12 19:22 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
> +            if (edmType == null && isUntyped)
>edmType == null && isUntyped [](http://example.com/codeflow?start=16&length=28)

so if edmType is (somehow) null, and isUntyped if false, will we now return null where previously we would throw an exception?

2023-05-12 19:23 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
> +            }
much better -- thanks!

2023-05-12 19:23 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +            // This's the workaround and when ODL fixes the issue, we should remove these codes.
so this code gets removed when we update our dependency to the latest ODL with this fix?

2023-05-12 19:24 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
> +        internal IEdmTypeReference TryGetEdmType(object instance, Type type)
:thumbsup:

2023-05-12 19:25 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +            }
doesn't look like it was addressed, but it's not a big deal either.

2023-05-12 19:26 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +                    // Once ODL supports, let's call the correct writing methods.
:thumbsup:

2023-05-12 19:30 UTC, mikepizzo commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +        private async Task WriteUntypedPropertiesAsync(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
I get that there is different logic for untyped versus typed, but I'm not sure why we can't invoke that separate logic when iterating through the list of typed properties, rather than doing the iteration twice. Not a big deal, but we may want to revisit this in the future, if customers complain about re-ordering properties.

2023-05-12 19:57 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
> +            // This's the workaround and when ODL fixes the issue, we should remove these codes.
I updated the comments

2023-05-12 19:58 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +            IODataEdmTypeSerializer resourceSetSerializer = SerializerProvider.GetEdmTypeSerializer(itemSetType);
basically, it's protected method, we can guarantee the input is not null. But, I can add a check to make sure it's valid.

2023-05-12 20:03 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
> +            if (edmType == null && isUntyped)
No, if 'isUntyped==false', it is the previous logic. Nothing changed.

2023-05-12 20:42 UTC, xuzhg commented on src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
> +            }
Already resolved. 1) Remove itemEdmtype != null for all. 2) Check itemEdmType at the beginning.

2023-05-12 22:47 UTC, mikepizzo approved these changes
:shipit:

2023-05-14 03:45 UTC, merged