Potential fix for issue #616
OData/AspNetCoreOData pull request #947
Opened 2023-05-31 06:12 UTC by orty

Based on issue #616 which I also encountered, I would like to propose this fix.

As I am not completely aware of side-effects that using only `edmProperty.Name` could have, I relied on a safe way to rollback to the EDM property name instead of the CLR one if the latter is not found.

https://github.com/OData/AspNetCoreOData/blob/10a246671b6312fd234151c47cc91787da5cb171/src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs#LL136C1-L145C18

2023-05-31 06:16 UTC, orty commented
> @microsoft-github-policy-service agree

2023-06-08 11:23 UTC, KenitoInc requested changes
Add tests

2023-06-08 12:26 UTC, orty commented
Hi @KenitoInc ,
I am a bit afraid of the amount of UT which would need an update to validate this scenario, but I will certainly give it a shot

2023-06-08 15:06 UTC, KenitoInc commented on test/Microsoft.AspNetCore.OData.Tests/Query/Query/DefaultSkipTokenHandlerTests.cs
> +        [InlineData("http://localhost/Customers?$expand=Orders", "http://localhost/Customers?$expand=Orders&$skiptoken=id-42")]
Add a test with $select

2023-06-08 15:52 UTC, orty commented on test/Microsoft.AspNetCore.OData.Tests/Query/Query/DefaultSkipTokenHandlerTests.cs
> +        [InlineData("http://localhost/Customers?$expand=Orders", "http://localhost/Customers?$expand=Orders&$skiptoken=id-42")]
Did it. I did not found a way to validate the `$skiptoken` generation in a context where `EnsureStableOrdering = true`. It seemed to me that in that case, query options like the following:
`http://localhost/Customers?$select=id&$orderby=name` 
should generate this kind of token: `http://localhost/Customers?$select=id&$orderby=name&$skiptoken=id-42%2Cname-%27ZX%27`

But that is not happening in this test method. Maybe something to add to another test class ?

2023-06-26 06:52 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +                    }
Thank you @orty for your pull request contribution.
I'd propose a simpler fix to this issue:
```suggestion
                    obj.TryGetPropertyValue(edmProperty.Name, out value);
```
I did a quick test and confirmed that it does the job.
If `lastMember` can be cast to `IEdmStructuredObject`, it should be okay to use the Edm property name to retrieve the property value from the object.
I didn't go to the extent of running all tests to confirm that nothing broke - let's try the change and see how it goes.

Note: We can also move the declaration for `clrPropertyName` to the `else` block since that's the only place where it'd be applicable/relevant.

2023-06-26 11:08 UTC, orty commented on src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
> +                    }
I did the change you suggested and I confirm it works like a charm. I went ahead and added some tests to check if an aliased model could also be handled like that, and discovered something.

In here :
https://github.com/OData/AspNetCoreOData/blob/118c2c175f49ebcf47fab64840bf4a8a675e8e8f/src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs#L431-L435

we should retrieve the proper underlying CLR type property name for the `IEdmProperty`, like it is done in the `QueryBinder.CreatePropertyAccessExpression` method, by adding `context.Model.GetClrPropertyName(property);`.

This is because, when the value-pairs dictionary has been populated, today it only works by chance that the `Expression` can be built here, in the `ApplyToCore` method
https://github.com/OData/AspNetCoreOData/blob/118c2c175f49ebcf47fab64840bf4a8a675e8e8f/src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs#L291-L296

It works with both PascalCased and LowerCamelCased propery names because of the permissivity of LINQ. When an alias is provided, it just throws an exception. With the next commit I will push this afternoon (it is 1PM here, gotta take a break ;)), the `Expression` is able to be built even with an alias.

I added all the subsequent unit tests for this change.

2023-06-29 07:55 UTC, gathogojr approved these changes
Thanks @orty for your contribution

2023-06-29 09:03 UTC, orty commented
> Thanks @orty for your contribution

You're welcome ! @KenitoInc, do you agree with the overall changes ?

2023-06-30 07:31 UTC, KenitoInc approved these changes

2023-06-30 08:16 UTC, merged

2023-06-30 12:53 UTC, KenitoInc commented
@orty Thanks for this PR