fixes #580
OData/AspNetCoreOData pull request #978
Opened 2023-07-02 11:24 UTC by mirgil

2023-07-02 11:28 UTC, mirgil commented
> @mirgil please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2023-07-12 09:05 UTC, xuzhg approved these changes

2023-07-25 16:53 UTC, mikepizzo requested changes
I believe the protocol expects these to be lower camel case. If so, changing this would be non-compliant.

2023-08-06 14:50 UTC, mirgil commented
> I believe the protocol expects these to be lower camel case. If so, changing this would be non-compliant.

Which protocol?
Serialization should be done according to the JsonSerializerOptions.PropertyNamingPolicy.
If no policy is defined, the original property (name and case) should be used.

2023-09-25 06:28 UTC, gathogojr commented
> I believe the protocol expects these to be lower camel case. If so, changing this would be non-compliant.

@mikepizzo I might be wrong but I think that the `PageResultValueConverter` is applicable in non-EDM scenarios - I don't think the `items`, `nextpagelink` and `count` property names used currently have anything to do with OData standard. @xuzhg can correct me if I'm wrong. Be that as it may, this PR has no tests to validate the changes.

Thank you @mirgil for you contribution. Could you please add tests to validate the changes?

2024-01-26 04:38 UTC, gathogojr commented on src/Microsoft.AspNetCore.OData/Results/PageResultValueConverter.cs
> +                return (JsonConverter)Activator.CreateInstance(
Hey @mirgil. Did you see Sam's comment here? @xuzhg Can you point the contributor to the class in the Netwtonsoft project where they need to apply a similar change?

2024-03-08 11:17 UTC, wachugamaina commented on src/Microsoft.AspNetCore.OData/Results/PageResultValueConverter.cs
> +            if (_namingPolicy == null)
if (_namingPolicy == null)
            {
                return name;
            }

           return _namingPolicy.ConvertName(name);

2024-03-08 11:18 UTC, wachugamaina commented
Could we have some tests for the new functionality ?

2025-01-12 10:03 UTC, closed without merging